### PR TITLE
Alert Dev iOS users to Forem iOS app

### PR DESCRIPTION
**Pull request by joshpuetz**
## Description

As outlined in https://github.com/forem/rfcs/issues/181, this PR adds an alert that informs users that the Forem iOS exists: the intent is to get users to migrate from the Dev iOS app to the Forem iOS app. Ideally we'd like to discontinue the Dev iOS app in the next few weeks. 

Upon app launch a sheet pops up tell users about the change, and gives them link to the App Store to down the Forem iOS app. After being dismissed users can redisplay the sheet via a "news" icon in the bottom tab bar.

Based on App Store Connect metrics: we have about 150 daily average active users that have opted into metrics. The majority of those users are on iOS > 15, but since our App Store listing for Dev iOS advertises compatibility with iOS 13 I've made the sheet backwards compatible with iOS 13 (and it was a **pain**!)

CleanShot 2021-11-18 at 10 39 05@2x

CleanShot 2021-11-18 at 10 38 22@2x

### Things that need some feedback:
- wording of the alert: I think we should actually tell users this app will be going away.
- sheet opening when app launches: right now the sheet opens every time the app is launched (but not on resume). Is this too much nagging?
- tab bar item (and coloring): I put a news type icon in the button bar and colored it to attract interest. Users can tap this icon to redisplay the sheet. Should we remove the icon color after the notice has been viewed? Should we even have an icon in the menubar?

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Related Tickets & Documents

closes https://github.com/forem/rfcs/issues/181

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

The sheet in action:
CleanShot 2021-11-23 at 14 17 15@2x

Notice the tab bar button at the bottom:

CleanShot 2021-11-17 at 15 45 39@2x

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

Breaking News

### CODE REVIEW

**Comment by fdoxyz** [comment]
Tried this out locally and looks pretty sweet!

> wording of the alert: I think we should actually tell users this app will be going away.

I totally agree with the idea of telling them "the DEV app will be discontinued". Maybe worth replacing the last sentence (quote below) with that message.

_"Don't worry about your profile information: it will be transferred to the Forem app"_

My reasoning (hypothesis) is that DEV users are "savvy enough" to know/expect to be able to log in to DEV on the new app. Maybe worth rephrasing as "enjoy the same DEV experience in the new app"? If necessary we can ultimately defer the final wording to `#content-review` (aka Gracie 😄)

> sheet opening when app launches: right now the sheet opens every time the app is launched (but not on resume). Is this too much nagging?

The app is going away so this sounds perfectly reasonable to me

> tab bar item (and coloring): I put a news type icon in the button bar and colored it to attract interest. Users can tap this icon to redisplay the sheet. Should we remove the icon color after the notice has been viewed? Should we even have an icon in the menubar?

I think the icon in the menubar is helpful to reach the AppStore link if dismissed. The color coding logic sounds like a nice to have that I'd be totally okay to leave with or without the tint altogether.

**Review by fdoxyz — APPROVED** [review]

**Comment by anujbhavsar96** [comment]
@joshpuetz This looks great😍.

> sheet opening when app launches: right now the sheet opens every time the app is launched (but not on resume). Is this too much nagging?

I think we shouldn't nag them every time. You just showcase popup once only. So they have knowledge about this. And if they still ignore the popup, we have news icon at the bottom.

Color is also fine. But once they click on the news icon once, maybe we can make it in black color. This is not a dealbreaker though🙂. 

**This is some nitpicking now😬**
Screenshot 2021-11-19 at 9 38 19 AM
It would be great if you can reduce the spacing between title and subtitle. Similar to subtitle and button.

**Comment by joshpuetz** [comment]
Thanks @fdoxyz and @anujbhavsar96! Here's what I've changed: 

- adjusted the padding to be even between title, text, and button
- changed the 'news' icon to be just black all the time (as coloring it would require me to store if the user has viewed it, which is getting to be a little much work for this simple feature!)
- changed the text, and will run it by #content-review

**Review by anujbhavsar96 — APPROVED** [review]

**Comment by SGGregory** [comment]
I'd suggest the following changes to the alert screen @joshpuetz:

**Heading:** Find DEV in the Forem app
**Sub-heading:** Get Forem for iOS in the App Store. Your DEV profile info will be carried over so you can pick up where you left off!

**Comment by leewynne** [comment]
Hey @joshpuetz 👋 quick question from me, I have previously deployed iOS versions of my Forems into the AppStore. I am still thinking about using them and updating them going forwards as maybe another growth/marketing mechanism alongside them being available in the Forem app.

Is there a simple line of code I can edit out here to switch this off if needed?

**Comment by leewynne** [comment]
Brilliant, thank you

**Pull request merged**
